/*
OpenAI API

APIs for sampling from and fine-tuning language models

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi-go

import (
	"encoding/json"
)

// CreateEditResponse struct for CreateEditResponse
type CreateEditResponse struct {
	Id string `json:"id"`
	Object string `json:"object"`
	Created int32 `json:"created"`
	Model string `json:"model"`
	Choices []CreateCompletionResponseChoicesInner `json:"choices"`
	Usage CreateCompletionResponseUsage `json:"usage"`
}

// NewCreateEditResponse instantiates a new CreateEditResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEditResponse(id string, object string, created int32, model string, choices []CreateCompletionResponseChoicesInner, usage CreateCompletionResponseUsage) *CreateEditResponse {
	this := CreateEditResponse{}
	this.Id = id
	this.Object = object
	this.Created = created
	this.Model = model
	this.Choices = choices
	this.Usage = usage
	return &this
}

// NewCreateEditResponseWithDefaults instantiates a new CreateEditResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEditResponseWithDefaults() *CreateEditResponse {
	this := CreateEditResponse{}
	return &this
}

// GetId returns the Id field value
func (o *CreateEditResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateEditResponse) GetIdOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateEditResponse) SetId(v string) {
	o.Id = v
}

// GetObject returns the Object field value
func (o *CreateEditResponse) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *CreateEditResponse) GetObjectOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *CreateEditResponse) SetObject(v string) {
	o.Object = v
}

// GetCreated returns the Created field value
func (o *CreateEditResponse) GetCreated() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *CreateEditResponse) GetCreatedOk() (*int32, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *CreateEditResponse) SetCreated(v int32) {
	o.Created = v
}

// GetModel returns the Model field value
func (o *CreateEditResponse) GetModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *CreateEditResponse) GetModelOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *CreateEditResponse) SetModel(v string) {
	o.Model = v
}

// GetChoices returns the Choices field value
func (o *CreateEditResponse) GetChoices() []CreateCompletionResponseChoicesInner {
	if o == nil {
		var ret []CreateCompletionResponseChoicesInner
		return ret
	}

	return o.Choices
}

// GetChoicesOk returns a tuple with the Choices field value
// and a boolean to check if the value has been set.
func (o *CreateEditResponse) GetChoicesOk() ([]CreateCompletionResponseChoicesInner, bool) {
	if o == nil {
    return nil, false
	}
	return o.Choices, true
}

// SetChoices sets field value
func (o *CreateEditResponse) SetChoices(v []CreateCompletionResponseChoicesInner) {
	o.Choices = v
}

// GetUsage returns the Usage field value
func (o *CreateEditResponse) GetUsage() CreateCompletionResponseUsage {
	if o == nil {
		var ret CreateCompletionResponseUsage
		return ret
	}

	return o.Usage
}

// GetUsageOk returns a tuple with the Usage field value
// and a boolean to check if the value has been set.
func (o *CreateEditResponse) GetUsageOk() (*CreateCompletionResponseUsage, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Usage, true
}

// SetUsage sets field value
func (o *CreateEditResponse) SetUsage(v CreateCompletionResponseUsage) {
	o.Usage = v
}

func (o CreateEditResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["object"] = o.Object
	}
	if true {
		toSerialize["created"] = o.Created
	}
	if true {
		toSerialize["model"] = o.Model
	}
	if true {
		toSerialize["choices"] = o.Choices
	}
	if true {
		toSerialize["usage"] = o.Usage
	}
	return json.Marshal(toSerialize)
}

type NullableCreateEditResponse struct {
	value *CreateEditResponse
	isSet bool
}

func (v NullableCreateEditResponse) Get() *CreateEditResponse {
	return v.value
}

func (v *NullableCreateEditResponse) Set(val *CreateEditResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEditResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEditResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEditResponse(val *CreateEditResponse) *NullableCreateEditResponse {
	return &NullableCreateEditResponse{value: val, isSet: true}
}

func (v NullableCreateEditResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEditResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


