/*
OpenAI API

APIs for sampling from and fine-tuning language models

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi-go

import (
	"encoding/json"
)

// CreateAnswerResponseSelectedDocumentsInner struct for CreateAnswerResponseSelectedDocumentsInner
type CreateAnswerResponseSelectedDocumentsInner struct {
	Document *int32 `json:"document,omitempty"`
	Text *string `json:"text,omitempty"`
}

// NewCreateAnswerResponseSelectedDocumentsInner instantiates a new CreateAnswerResponseSelectedDocumentsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAnswerResponseSelectedDocumentsInner() *CreateAnswerResponseSelectedDocumentsInner {
	this := CreateAnswerResponseSelectedDocumentsInner{}
	return &this
}

// NewCreateAnswerResponseSelectedDocumentsInnerWithDefaults instantiates a new CreateAnswerResponseSelectedDocumentsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAnswerResponseSelectedDocumentsInnerWithDefaults() *CreateAnswerResponseSelectedDocumentsInner {
	this := CreateAnswerResponseSelectedDocumentsInner{}
	return &this
}

// GetDocument returns the Document field value if set, zero value otherwise.
func (o *CreateAnswerResponseSelectedDocumentsInner) GetDocument() int32 {
	if o == nil || isNil(o.Document) {
		var ret int32
		return ret
	}
	return *o.Document
}

// GetDocumentOk returns a tuple with the Document field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAnswerResponseSelectedDocumentsInner) GetDocumentOk() (*int32, bool) {
	if o == nil || isNil(o.Document) {
    return nil, false
	}
	return o.Document, true
}

// HasDocument returns a boolean if a field has been set.
func (o *CreateAnswerResponseSelectedDocumentsInner) HasDocument() bool {
	if o != nil && !isNil(o.Document) {
		return true
	}

	return false
}

// SetDocument gets a reference to the given int32 and assigns it to the Document field.
func (o *CreateAnswerResponseSelectedDocumentsInner) SetDocument(v int32) {
	o.Document = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *CreateAnswerResponseSelectedDocumentsInner) GetText() string {
	if o == nil || isNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAnswerResponseSelectedDocumentsInner) GetTextOk() (*string, bool) {
	if o == nil || isNil(o.Text) {
    return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *CreateAnswerResponseSelectedDocumentsInner) HasText() bool {
	if o != nil && !isNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *CreateAnswerResponseSelectedDocumentsInner) SetText(v string) {
	o.Text = &v
}

func (o CreateAnswerResponseSelectedDocumentsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Document) {
		toSerialize["document"] = o.Document
	}
	if !isNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	return json.Marshal(toSerialize)
}

type NullableCreateAnswerResponseSelectedDocumentsInner struct {
	value *CreateAnswerResponseSelectedDocumentsInner
	isSet bool
}

func (v NullableCreateAnswerResponseSelectedDocumentsInner) Get() *CreateAnswerResponseSelectedDocumentsInner {
	return v.value
}

func (v *NullableCreateAnswerResponseSelectedDocumentsInner) Set(val *CreateAnswerResponseSelectedDocumentsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAnswerResponseSelectedDocumentsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAnswerResponseSelectedDocumentsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAnswerResponseSelectedDocumentsInner(val *CreateAnswerResponseSelectedDocumentsInner) *NullableCreateAnswerResponseSelectedDocumentsInner {
	return &NullableCreateAnswerResponseSelectedDocumentsInner{value: val, isSet: true}
}

func (v NullableCreateAnswerResponseSelectedDocumentsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAnswerResponseSelectedDocumentsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


