/*
OpenAI API

APIs for sampling from and fine-tuning language models

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi-go

import (
	"encoding/json"
)

// CreateAnswerResponse struct for CreateAnswerResponse
type CreateAnswerResponse struct {
	Object *string `json:"object,omitempty"`
	Model *string `json:"model,omitempty"`
	SearchModel *string `json:"search_model,omitempty"`
	Completion *string `json:"completion,omitempty"`
	Answers []string `json:"answers,omitempty"`
	SelectedDocuments []CreateAnswerResponseSelectedDocumentsInner `json:"selected_documents,omitempty"`
}

// NewCreateAnswerResponse instantiates a new CreateAnswerResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAnswerResponse() *CreateAnswerResponse {
	this := CreateAnswerResponse{}
	return &this
}

// NewCreateAnswerResponseWithDefaults instantiates a new CreateAnswerResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAnswerResponseWithDefaults() *CreateAnswerResponse {
	this := CreateAnswerResponse{}
	return &this
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *CreateAnswerResponse) GetObject() string {
	if o == nil || isNil(o.Object) {
		var ret string
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAnswerResponse) GetObjectOk() (*string, bool) {
	if o == nil || isNil(o.Object) {
    return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *CreateAnswerResponse) HasObject() bool {
	if o != nil && !isNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given string and assigns it to the Object field.
func (o *CreateAnswerResponse) SetObject(v string) {
	o.Object = &v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *CreateAnswerResponse) GetModel() string {
	if o == nil || isNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAnswerResponse) GetModelOk() (*string, bool) {
	if o == nil || isNil(o.Model) {
    return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *CreateAnswerResponse) HasModel() bool {
	if o != nil && !isNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *CreateAnswerResponse) SetModel(v string) {
	o.Model = &v
}

// GetSearchModel returns the SearchModel field value if set, zero value otherwise.
func (o *CreateAnswerResponse) GetSearchModel() string {
	if o == nil || isNil(o.SearchModel) {
		var ret string
		return ret
	}
	return *o.SearchModel
}

// GetSearchModelOk returns a tuple with the SearchModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAnswerResponse) GetSearchModelOk() (*string, bool) {
	if o == nil || isNil(o.SearchModel) {
    return nil, false
	}
	return o.SearchModel, true
}

// HasSearchModel returns a boolean if a field has been set.
func (o *CreateAnswerResponse) HasSearchModel() bool {
	if o != nil && !isNil(o.SearchModel) {
		return true
	}

	return false
}

// SetSearchModel gets a reference to the given string and assigns it to the SearchModel field.
func (o *CreateAnswerResponse) SetSearchModel(v string) {
	o.SearchModel = &v
}

// GetCompletion returns the Completion field value if set, zero value otherwise.
func (o *CreateAnswerResponse) GetCompletion() string {
	if o == nil || isNil(o.Completion) {
		var ret string
		return ret
	}
	return *o.Completion
}

// GetCompletionOk returns a tuple with the Completion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAnswerResponse) GetCompletionOk() (*string, bool) {
	if o == nil || isNil(o.Completion) {
    return nil, false
	}
	return o.Completion, true
}

// HasCompletion returns a boolean if a field has been set.
func (o *CreateAnswerResponse) HasCompletion() bool {
	if o != nil && !isNil(o.Completion) {
		return true
	}

	return false
}

// SetCompletion gets a reference to the given string and assigns it to the Completion field.
func (o *CreateAnswerResponse) SetCompletion(v string) {
	o.Completion = &v
}

// GetAnswers returns the Answers field value if set, zero value otherwise.
func (o *CreateAnswerResponse) GetAnswers() []string {
	if o == nil || isNil(o.Answers) {
		var ret []string
		return ret
	}
	return o.Answers
}

// GetAnswersOk returns a tuple with the Answers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAnswerResponse) GetAnswersOk() ([]string, bool) {
	if o == nil || isNil(o.Answers) {
    return nil, false
	}
	return o.Answers, true
}

// HasAnswers returns a boolean if a field has been set.
func (o *CreateAnswerResponse) HasAnswers() bool {
	if o != nil && !isNil(o.Answers) {
		return true
	}

	return false
}

// SetAnswers gets a reference to the given []string and assigns it to the Answers field.
func (o *CreateAnswerResponse) SetAnswers(v []string) {
	o.Answers = v
}

// GetSelectedDocuments returns the SelectedDocuments field value if set, zero value otherwise.
func (o *CreateAnswerResponse) GetSelectedDocuments() []CreateAnswerResponseSelectedDocumentsInner {
	if o == nil || isNil(o.SelectedDocuments) {
		var ret []CreateAnswerResponseSelectedDocumentsInner
		return ret
	}
	return o.SelectedDocuments
}

// GetSelectedDocumentsOk returns a tuple with the SelectedDocuments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAnswerResponse) GetSelectedDocumentsOk() ([]CreateAnswerResponseSelectedDocumentsInner, bool) {
	if o == nil || isNil(o.SelectedDocuments) {
    return nil, false
	}
	return o.SelectedDocuments, true
}

// HasSelectedDocuments returns a boolean if a field has been set.
func (o *CreateAnswerResponse) HasSelectedDocuments() bool {
	if o != nil && !isNil(o.SelectedDocuments) {
		return true
	}

	return false
}

// SetSelectedDocuments gets a reference to the given []CreateAnswerResponseSelectedDocumentsInner and assigns it to the SelectedDocuments field.
func (o *CreateAnswerResponse) SetSelectedDocuments(v []CreateAnswerResponseSelectedDocumentsInner) {
	o.SelectedDocuments = v
}

func (o CreateAnswerResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	if !isNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !isNil(o.SearchModel) {
		toSerialize["search_model"] = o.SearchModel
	}
	if !isNil(o.Completion) {
		toSerialize["completion"] = o.Completion
	}
	if !isNil(o.Answers) {
		toSerialize["answers"] = o.Answers
	}
	if !isNil(o.SelectedDocuments) {
		toSerialize["selected_documents"] = o.SelectedDocuments
	}
	return json.Marshal(toSerialize)
}

type NullableCreateAnswerResponse struct {
	value *CreateAnswerResponse
	isSet bool
}

func (v NullableCreateAnswerResponse) Get() *CreateAnswerResponse {
	return v.value
}

func (v *NullableCreateAnswerResponse) Set(val *CreateAnswerResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAnswerResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAnswerResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAnswerResponse(val *CreateAnswerResponse) *NullableCreateAnswerResponse {
	return &NullableCreateAnswerResponse{value: val, isSet: true}
}

func (v NullableCreateAnswerResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAnswerResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


