/*
OpenAI API

APIs for sampling from and fine-tuning language models

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi-go

import (
	"encoding/json"
)

// CreateClassificationResponse struct for CreateClassificationResponse
type CreateClassificationResponse struct {
	Object *string `json:"object,omitempty"`
	Model *string `json:"model,omitempty"`
	SearchModel *string `json:"search_model,omitempty"`
	Completion *string `json:"completion,omitempty"`
	Label *string `json:"label,omitempty"`
	SelectedExamples []CreateClassificationResponseSelectedExamplesInner `json:"selected_examples,omitempty"`
}

// NewCreateClassificationResponse instantiates a new CreateClassificationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateClassificationResponse() *CreateClassificationResponse {
	this := CreateClassificationResponse{}
	return &this
}

// NewCreateClassificationResponseWithDefaults instantiates a new CreateClassificationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateClassificationResponseWithDefaults() *CreateClassificationResponse {
	this := CreateClassificationResponse{}
	return &this
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *CreateClassificationResponse) GetObject() string {
	if o == nil || isNil(o.Object) {
		var ret string
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClassificationResponse) GetObjectOk() (*string, bool) {
	if o == nil || isNil(o.Object) {
    return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *CreateClassificationResponse) HasObject() bool {
	if o != nil && !isNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given string and assigns it to the Object field.
func (o *CreateClassificationResponse) SetObject(v string) {
	o.Object = &v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *CreateClassificationResponse) GetModel() string {
	if o == nil || isNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClassificationResponse) GetModelOk() (*string, bool) {
	if o == nil || isNil(o.Model) {
    return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *CreateClassificationResponse) HasModel() bool {
	if o != nil && !isNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *CreateClassificationResponse) SetModel(v string) {
	o.Model = &v
}

// GetSearchModel returns the SearchModel field value if set, zero value otherwise.
func (o *CreateClassificationResponse) GetSearchModel() string {
	if o == nil || isNil(o.SearchModel) {
		var ret string
		return ret
	}
	return *o.SearchModel
}

// GetSearchModelOk returns a tuple with the SearchModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClassificationResponse) GetSearchModelOk() (*string, bool) {
	if o == nil || isNil(o.SearchModel) {
    return nil, false
	}
	return o.SearchModel, true
}

// HasSearchModel returns a boolean if a field has been set.
func (o *CreateClassificationResponse) HasSearchModel() bool {
	if o != nil && !isNil(o.SearchModel) {
		return true
	}

	return false
}

// SetSearchModel gets a reference to the given string and assigns it to the SearchModel field.
func (o *CreateClassificationResponse) SetSearchModel(v string) {
	o.SearchModel = &v
}

// GetCompletion returns the Completion field value if set, zero value otherwise.
func (o *CreateClassificationResponse) GetCompletion() string {
	if o == nil || isNil(o.Completion) {
		var ret string
		return ret
	}
	return *o.Completion
}

// GetCompletionOk returns a tuple with the Completion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClassificationResponse) GetCompletionOk() (*string, bool) {
	if o == nil || isNil(o.Completion) {
    return nil, false
	}
	return o.Completion, true
}

// HasCompletion returns a boolean if a field has been set.
func (o *CreateClassificationResponse) HasCompletion() bool {
	if o != nil && !isNil(o.Completion) {
		return true
	}

	return false
}

// SetCompletion gets a reference to the given string and assigns it to the Completion field.
func (o *CreateClassificationResponse) SetCompletion(v string) {
	o.Completion = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *CreateClassificationResponse) GetLabel() string {
	if o == nil || isNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClassificationResponse) GetLabelOk() (*string, bool) {
	if o == nil || isNil(o.Label) {
    return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *CreateClassificationResponse) HasLabel() bool {
	if o != nil && !isNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *CreateClassificationResponse) SetLabel(v string) {
	o.Label = &v
}

// GetSelectedExamples returns the SelectedExamples field value if set, zero value otherwise.
func (o *CreateClassificationResponse) GetSelectedExamples() []CreateClassificationResponseSelectedExamplesInner {
	if o == nil || isNil(o.SelectedExamples) {
		var ret []CreateClassificationResponseSelectedExamplesInner
		return ret
	}
	return o.SelectedExamples
}

// GetSelectedExamplesOk returns a tuple with the SelectedExamples field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClassificationResponse) GetSelectedExamplesOk() ([]CreateClassificationResponseSelectedExamplesInner, bool) {
	if o == nil || isNil(o.SelectedExamples) {
    return nil, false
	}
	return o.SelectedExamples, true
}

// HasSelectedExamples returns a boolean if a field has been set.
func (o *CreateClassificationResponse) HasSelectedExamples() bool {
	if o != nil && !isNil(o.SelectedExamples) {
		return true
	}

	return false
}

// SetSelectedExamples gets a reference to the given []CreateClassificationResponseSelectedExamplesInner and assigns it to the SelectedExamples field.
func (o *CreateClassificationResponse) SetSelectedExamples(v []CreateClassificationResponseSelectedExamplesInner) {
	o.SelectedExamples = v
}

func (o CreateClassificationResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	if !isNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !isNil(o.SearchModel) {
		toSerialize["search_model"] = o.SearchModel
	}
	if !isNil(o.Completion) {
		toSerialize["completion"] = o.Completion
	}
	if !isNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !isNil(o.SelectedExamples) {
		toSerialize["selected_examples"] = o.SelectedExamples
	}
	return json.Marshal(toSerialize)
}

type NullableCreateClassificationResponse struct {
	value *CreateClassificationResponse
	isSet bool
}

func (v NullableCreateClassificationResponse) Get() *CreateClassificationResponse {
	return v.value
}

func (v *NullableCreateClassificationResponse) Set(val *CreateClassificationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateClassificationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateClassificationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateClassificationResponse(val *CreateClassificationResponse) *NullableCreateClassificationResponse {
	return &NullableCreateClassificationResponse{value: val, isSet: true}
}

func (v NullableCreateClassificationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateClassificationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


